apiVersion: "monitoring.coreos.com/v1"
kind: "ServiceMonitor"
metadata:
  name: "longhorn-manager"
  namespace: "longhorn-system"
  labels:
    release: "prom-operator"
spec:
  selector:
    matchLabels:
      app: "longhorn-manager"
  endpoints:
    - port: "manager"
      interval: "30s"
      honorLabels: true

---
apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "longhorn-rules"
  namespace: "longhorn-system"
  labels:
    release: "prom-operator"
spec:
  groups:
    - name: "longhorn.rules"
      rules:
        - alert: "LonghornVolumeUsageCritical"
          expr: '100 * (longhorn_volume_usage_bytes / longhorn_volume_capacity_bytes) > 90'
          for: "5m"
          labels:
            issue: "Longhorn volume {{$labels.volume}} usage on {{$labels.node}} is critical."
            severity: "critical"
          annotations:
            summary: "Longhorn volume capacity is over 90% used."
            description: "Longhorn volume {{$labels.volume}} on {{$labels.node}} is at {{$value}}% used for more than 5 minutes."
