loki:
  image:
    tag: "2.9.6"
    registry: "docker.io"
    repository: "grafana/loki"
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2023-01-05"
        store: "tsdb"
        schema: "v12"
        object_store: "{{ .Values.loki.storage.type }}"
        index:
          prefix: "index_"
          period: "24h"
  storage:
    type: "filesystem"
  server:
    log_level: "info"
    http_server_read_timeout: "500s"
    http_server_write_timeout: "500s"
    grpc_server_max_recv_msg_size: 134217728
    grpc_server_max_send_msg_size: 134217728
  frontend:
    compress_responses: true
    log_queries_longer_than: "20s"
  frontend_worker:
    parallelism: 10
    match_max_concurrent: false
  querier:
    max_concurrent: 10
  query_scheduler:
    max_outstanding_requests_per_tenant: 32768
  compactor:
    compaction_interval: "10m"
  ingester:
    chunk_idle_period: "5m"
    chunk_retain_period: "1m"
  limits_config:
    query_timeout: "500s"
    enforce_metric_name: false
    reject_old_samples: true
    ingestion_rate_mb: 50
    ingestion_burst_size_mb: 70
    reject_old_samples_max_age: "72h"
    split_queries_by_interval: "15m"
    max_query_parallelism: 32
    max_cache_freshness_per_query: "10m"

singleBinary:
  replicas: 1
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"
    promtail.io/collect: "true"
  resources:
    requests:
      memory: "850Mi"
    limits:
      memory: "850Mi"
  persistence:
    volumeClaimsEnabled: true
    storageClass: "local-path"
    size: "6Gi"

ingress:
  enabled: true
  hosts: ["grafana-loki.k3s"]
  ingressClassName: "nginx"

gateway:
  enabled: false

test:
  enabled: false

monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
    alerting: false
  serviceMonitor:
    enabled: true
    interval: "1m"
    labels:
      release: "prom-operator"
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false
