apiVersion: "monitoring.coreos.com/v1"
kind: "PodMonitor"
metadata:
  name: "fluent-bit"
  namespace: "monitoring"
  labels:
    release: "prom-operator"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "fluent-bit"
  podMetricsEndpoints:
    - port: "metrics"
      path: "/api/v1/metrics/prometheus"
      honorLabels: true
      scrapeTimeout: "30s"
