apiVersion: "elasticsearch.k8s.elastic.co/v1"
kind: "Elasticsearch"
metadata:
  name: "es"
  namespace: "monitoring"
spec:
  version: "8.10.4"
  nodeSets:
    - name: "default"
      count: 1
      config:
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: "elasticsearch-data"
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "local-path"
            resources:
              requests:
                storage: "6Gi"
