falco:
  grpcUnixSocketPath: "unix:///run/falco/falco.sock"

resources:
  requests:
    memory: "32Mi"
  limits:
    memory: "64Mi"

serviceMonitor:
  enabled: true
  interval: "30s"
  additionalLabels:
    release: "prom-operator"

nodeSelector:
  kubernetes.io/os: "linux"

tolerations:
  - operator: "Exists"
