apiVersion: "v1"
kind: "Service"
metadata:
  name: "beyla-test-app"
  namespace: "testing"
spec:
  selector:
    app.kubernetes.io/name: "beyla-test-app"
  ports:
    - name: "http"
      port: 8080
      targetPort: "http"
    - name: "metrics"
      port: 8443
      targetPort: "metrics"

---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "beyla-test-app"
  namespace: "testing"
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app.kubernetes.io/name: "beyla-test-app"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "beyla-test-app"
      annotations:
        promtail.io/collect: "true"
    spec:
      shareProcessNamespace: true
      automountServiceAccountToken: false
      containers:
        - name: "web-app"
          image: "traefik/whoami:latest"
          imagePullPolicy: "IfNotPresent"
          args: ["-port=8080"]
          ports:
            - name: "http"
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]

        - name: "app-sidecar"
          image: "grafana/beyla:latest"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: "BEYLA_SERVICE_NAME"
              value: "whoami"
            - name: "BEYLA_OPEN_PORT"
              value: "8080"
            - name: "BEYLA_PRINT_TRACES"
              value: "true"
            - name: "BEYLA_LOG_LEVEL"
              value: "DEBUG"
            - name: "BEYLA_PROMETHEUS_PORT"
              value: "8443"
            - name: "BEYLA_PROMETHEUS_PATH"
              value: "/metrics"
          ports:
            - name: "metrics"
              containerPort: 8443
          securityContext:
            privileged: true
            runAsUser: 0
            capabilities:
              add: ["SYS_ADMIN"]
