apiVersion: "monitoring.coreos.com/v1"
kind: "ServiceMonitor"
metadata:
  name: "karpenter"
  namespace: "monitoring"
  labels:
    release: "prom-operator"
spec:
  namespaceSelector:
    matchNames:
      - "kube-system"
  selector:
    matchLabels:
      app.kubernetes.io/name: "karpenter"
  endpoints:
    - port: "http-metrics"
      interval: "30s"
      honorLabels: true
