apiVersion: "monitoring.coreos.com/v1"
kind: "ServiceMonitor"
metadata:
  name: "keptn-monitor"
  namespace: "keptn-system"
  labels:
    release: "prom-operator"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "keptn"
      app.kubernetes.io/name: "lifecycle-operator"
  endpoints:
    - port: "metrics"
      interval: "30s"
      honorLabels: true
