apiVersion: "cert-manager.io/v1"
kind: "Certificate"
metadata:
  name: "keptn-certs"
  namespace: "keptn-system"
spec:
  dnsNames:
    - "lifecycle-webhook-service.keptn-system.svc"
    - "lifecycle-webhook-service.keptn-system.svc.cluster.local"
    - "metrics-webhook-service.keptn-system.svc"
    - "metrics-webhook-service.keptn-system.svc.cluster.local"
  issuerRef:
    kind: "ClusterIssuer"
    name: "k8s-cluster-issuer"
  secretName: "keptn-certs"
