apiVersion: "batch/v1"
kind: "CronJob"
metadata:
  name: "grafana-backup"
  namespace: "testing"
spec:
  schedule: "@weekly"
  jobTemplate:
    metadata:
      labels:
        app: "grafana-backup"
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: "grafana-backup"
              image: "ysde/docker-grafana-backup-tool:1.4.2"
              imagePullPolicy: "IfNotPresent"
              env:
                - name: "VERIFY_SSL"
                  value: "False"
                - name: "GRAFANA_URL"
                  value: "http://prom-operator-grafana.monitoring.svc:80"
                - name: "GRAFANA_TOKEN"
                  value: "glsa_c42xcSSH98ZKol5NMIacGls3Gxlao8ae_cdc6a6b1"
                - name: "GRAFANA_ADMIN_ACCOUNT"
                  value: "admin"
                - name: "GRAFANA_ADMIN_PASSWORD"
                  value: "prom-operator"
                - name: "AWS_ENDPOINT_URL"
                  value: "http://s3-minio.testing.svc:9000"
                - name: "AWS_S3_BUCKET_NAME"
                  value: "backups"
                - name: "AWS_S3_BUCKET_KEY"
                  value: "grafana"
                - name: "AWS_ACCESS_KEY_ID"
                  value: "testing"
                - name: "AWS_SECRET_ACCESS_KEY"
                  value: "1qaz!QAZ"
