apiVersion: "monitoring.coreos.com/v1"
kind: "PodMonitor"
metadata:
  name: "argocd-components"
  namespace: "monitoring"
  labels:
    release: "prom-operator"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "argocd"
      app.kubernetes.io/part-of: "argocd"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: "metrics"
      interval: "1m"
      honorLabels: true
