apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "argo-workflows-ui"
rules:
  - apiGroups: [""]
    resources:
      - "pods"
      - "events"
      - "pods/log"
      - "namespaces"
    verbs: ["list", "get", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["sensors"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["eventbus"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["eventsources"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workfloweventbindings"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["cronworkflows"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtemplates"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["clusterworkflowtemplates"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtasksets"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflowartifactgctasks"]
    verbs: ["list", "get", "watch"]

---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "argo-workflows-ui"
  namespace: "argo-workflows"

---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "argo-workflows-ui"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "argo-workflows-ui"
subjects:
  - kind: "ServiceAccount"
    name: "argo-workflows-ui"
    namespace: "argo-workflows"

---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "argo-workflows-ui.service-account-token"
  namespace: "argo-workflows"
  annotations:
    kubernetes.io/service-account.name: "argo-workflows-ui"
type: "kubernetes.io/service-account-token"
