apiVersion: "monitoring.coreos.com/v1"
kind: "ServiceMonitor"
metadata:
  name: "argo-workflows-monitor"
  namespace: "argo-workflows"
  labels:
    release: "prom-operator"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "argo-workflows-workflow-controller"
      app.kubernetes.io/instance: "argo-workflows"
  endpoints:
    - port: "metrics"
      interval: "30s"
      honorLabels: true
