annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"

resources:
  requests:
    memory: "128Mi"
  limits:
    memory: "128Mi"

logging:
  enabled: true
  fluentbit:
    metrics:
      prometheusAnnotations: true
      serviceMonitor: true
      serviceMonitorConfig:
        additionalLabels:
          release: "prom-operator"
    resources:
      requests:
        memory: "128Mi"
      limits:
        memory: "128Mi"
    nodeSelector:
      kubernetes.io/os: "linux"
    tolerations:
      - operator: "Exists"
  fluentd:
    metrics:
      prometheusAnnotations: true
      serviceMonitor: true
      serviceMonitorConfig:
        additionalLabels:
          release: "prom-operator"
    resources:
      requests:
        memory: "512Mi"
      limits:
        memory: "512Mi"
    bufferStorageVolume:
      pvc:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "local-path"
          resources:
            requests:
              storage: "4G"
  eventTailer:
    pvc:
      storage: "512Mi"
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-path"
  hostTailer:
    workloadOverrides:
      nodeSelector:
        kubernetes.io/os: "linux"
      tolerations:
        - operator: "Exists"
    systemdTailers:
      - name: "k3s-master"
        maxEntries: 100
        systemdFilter: "k3s.service"
      - name: "k3s-agent"
        maxEntries: 100
        systemdFilter: "k3s-agent.service"

monitoring:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: "prom-operator"
