apiVersion: "v1"
kind: "Node"
metadata:
  name: "kwok-node-0"
  labels:
    beta.kubernetes.io/arch: "amd64"
    beta.kubernetes.io/os: "linux"
    kubernetes.io/arch: "amd64"
    kubernetes.io/hostname: "kwok-node-0"
    kubernetes.io/os: "linux"
    kubernetes.io/role: "agent"
    node-role.kubernetes.io/agent: ""
    type: "kwok"
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    kwok.x-k8s.io/node: "fake"
spec:
  taints:
    - effect: "NoSchedule"
      key: "kwok.x-k8s.io/node"
      value: "fake"
status:
  allocatable:
    cpu: 4
    memory: "16Gi"
    pods: 100
  capacity:
    cpu: 4
    memory: "16Gi"
    pods: 100
  nodeInfo:
    architecture: "amd64"
    bootID: ""
    containerRuntimeVersion: ""
    kernelVersion: ""
    kubeProxyVersion: "fake"
    kubeletVersion: "fake"
    machineID: ""
    operatingSystem: "linux"
    osImage: ""
    systemUUID: ""
  phase: "Running"
