apiVersion: "monitoring.coreos.com/v1"
kind: "PodMonitor"
metadata:
  name: "ingress-nginx-controllers"
  namespace: "monitoring"
  labels:
    release: "prom-operator"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "ingress-nginx"
      app.kubernetes.io/component: "controller"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: "metrics"
      interval: "1m"
      honorLabels: true
