apiVersion: "cilium.io/v1alpha1"
kind: "TracingPolicy"
metadata:
  name: "monitor-network-activity-outside-cluster-cidr-range"
spec:
  kprobes:
    - call: "tcp_connect"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchArgs:
            - index: 0
              operator: "NotDAddr"
              values:
                - "127.0.0.1/8"
                - "10.42.0.0/16"
                - "10.43.0.0/16"
                - "192.168.55.0/24"
                - "192.168.56.0/24"
                - "192.168.168.0/24"
                - "192.168.207.0/25"
                - "192.168.207.128/25"
