infoMetric: true
statusInMetric: true
timestampMetric: true
latestChartVersion: false

grafanaDashboard:
  enabled: true

resources:
  requests:
    memory: "192Mi"
  limits:
    memory: "192Mi"

nodeSelector:
  kubernetes.io/os: "linux"

serviceMonitor:
  create: true
  interval: "30s"
  additionalLabels:
    release: "prom-operator"
