apiVersion: "monitoring.coreos.com/v1"
kind: "ServiceMonitor"
metadata:
  name: "cert-manager"
  namespace: "cert-manager"
  labels:
    release: "prom-operator"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "cert-manager"
      app.kubernetes.io/component: "controller"
  endpoints:
    - port: "tcp-prometheus-servicemonitor"
      interval: "1m"
      honorLabels: true
