# Allowed values: standalone or replication
architecture: "standalone"

auth:
  enabled: false
  sentinel: false
  password: ""

master:
  count: 1
  podAnnotations:
    promtail.io/collect: "true"
  persistence:
    enabled: true
    size: "2Gi"
    accessModes: ["ReadWriteOnce"]
    storageClass: "local-path"
  resources:
    limits: {}
    requests: {}
  nodeSelector:
    kubernetes.io/os: "linux"

replica:
  replicaCount: 1
  podAnnotations:
    promtail.io/collect: "true"
  persistence:
    enabled: true
    size: "2Gi"
    accessModes: ["ReadWriteOnce"]
    storageClass: "local-path"
  resources:
    limits: {}
    requests: {}
  nodeSelector:
    kubernetes.io/os: "linux"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: "1m"
    additionalLabels:
      release: "prom-operator"
